/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerStats = IDL.Record({
  'wins' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'totalKills' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Timestamp = IDL.Int;
export const Notification = IDL.Record({
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const QuestionRecord = IDL.Record({
  'question' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Mode = IDL.Variant({ 'child' : IDL.Null, 'parent' : IDL.Null });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUpdatePlayerStats' : IDL.Func([IDL.Principal, PlayerStats], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateParentMode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPlayerStats' : IDL.Func([], [IDL.Opt(PlayerStats)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPlayerStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerStats)],
      ['query'],
    ),
  'getQuestionHistory' : IDL.Func([], [IDL.Vec(QuestionRecord)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isParentPinSet' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'recordQuestion' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setParentPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'switchMode' : IDL.Func([], [Mode], []),
  'updatePlayerStats' : IDL.Func([PlayerStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerStats = IDL.Record({
    'wins' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'totalKills' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Timestamp = IDL.Int;
  const Notification = IDL.Record({
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const QuestionRecord = IDL.Record({
    'question' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const Mode = IDL.Variant({ 'child' : IDL.Null, 'parent' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUpdatePlayerStats' : IDL.Func([IDL.Principal, PlayerStats], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateParentMode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPlayerStats' : IDL.Func([], [IDL.Opt(PlayerStats)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPlayerStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerStats)],
        ['query'],
      ),
    'getQuestionHistory' : IDL.Func([], [IDL.Vec(QuestionRecord)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isParentPinSet' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'recordQuestion' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setParentPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'switchMode' : IDL.Func([], [Mode], []),
    'updatePlayerStats' : IDL.Func([PlayerStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };