/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Mode = { 'child' : null } |
  { 'parent' : null };
export interface Notification {
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface PlayerStats {
  'wins' : bigint,
  'matchesPlayed' : bigint,
  'totalKills' : bigint,
}
export interface QuestionRecord { 'question' : string, 'timestamp' : Timestamp }
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUpdatePlayerStats' : ActorMethod<[Principal, PlayerStats], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateParentMode' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPlayerStats' : ActorMethod<[], [] | [PlayerStats]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPlayerStats' : ActorMethod<[Principal], [] | [PlayerStats]>,
  'getQuestionHistory' : ActorMethod<[], Array<QuestionRecord>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isParentPinSet' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'recordQuestion' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setParentPin' : ActorMethod<[string], boolean>,
  'switchMode' : ActorMethod<[], Mode>,
  'updatePlayerStats' : ActorMethod<[PlayerStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];